<a href="https://colab.research.google.com/github/alagiehafigue/ai-ml-engineering/blob/main/unsupervised_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
df = pd.read_csv('customer_segments.csv')

df.head()

   customer_id  age  monthly_spend_ghs  cluster
0            1   20                 80        0
1            2   21                100        0
2            3   22                120        0
3            4   22                140        0
4            5   23                160        0

In [31]:
df.shape

(40, 4)

In [32]:
df[df['cluster'] == 0].count()

customer_id          18
age                  18
monthly_spend_ghs    18
cluster              18
dtype: int64

In [33]:
df[df['cluster'] == 1].mean()

customer_id           25.000000
age                   43.846154
monthly_spend_ghs    973.076923
cluster                1.000000
dtype: float64

In [34]:
cluster_2 = df[df['cluster'] == 2]
cluster_2['age'].mean()

np.float64(64.55555555555556)